blank_issues_enabled: false
contact_links:
  - name: Ask a question / Саволу ҷавоб (Чат)
    url: https://t.me/tajgramTips
    about: Please ask and answer questions here / Саволҳои худро дар ин ҷо пурсед ва ҷавоб гиред.
  - name: Official Tajgram Channel / Канали расмии Tajgram
    url: https://t.me/tajgramTips
    about: Subscribe for notifications and new releases / Барои гирифтани хабарҳо ва релизҳои нав обуна шавед.
