package org.telegram.messenger;
import android.content.Context;
import android.content.SharedPreferences;
import android.widget.Toast;
import com.google.firebase.database.*;
import java.io.*;
import java.util.*;
import org.xmlpull.v1.XmlPullParser;
import android.util.Xml;
public class JokeManager {
    private static final String PREFS_NAME = "TajgramJokeSecretPrefs";
    private static DatabaseReference databaseRef;
    private static DatabaseReference getDatabase() { if (databaseRef == null) { try { databaseRef = FirebaseDatabase.getInstance().getReference("tajgram_app_substitutions"); } catch (Exception e) {} } return databaseRef; }
    public static int getChangedCount(Context context) { return context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE).getInt("changed_strings_count", 0); }
    public static boolean isLocked24h(Context context) { SharedPreferences prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE); long lockTime = prefs.getLong("lock_timestamp", 0); if (lockTime == 0) return false; if (System.currentTimeMillis() - lockTime < 86400000) return true; else { prefs.edit().putLong("lock_timestamp", 0).putInt("bad_attempts", 0).apply(); return false; } }
    public static String handleSubstitutions(Context context, String userText, String userLanguage) { SharedPreferences prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE); String cleanedText = userText.toLowerCase().trim(); if (cleanedText.contains("хақорат") || cleanedText.contains("мат") || cleanedText.contains("безеб")) { int attempts = prefs.getInt("bad_attempts", 0) + 1; prefs.edit().putInt("bad_attempts", attempts).apply(); if (attempts >= 3) { prefs.edit().putLong("lock_timestamp", System.currentTimeMillis()).apply(); return "BLOCK_24H"; } return "Warning!"; } ArrayList<String> jokesList = new ArrayList<>(); try { String targetLang = userLanguage != null ? userLanguage.toLowerCase() : "values"; List<String> supportedLangs = Arrays.asList("ar", "be", "fa", "kk", "ky", "ru", "tg", "uz"); if (!supportedLangs.contains(targetLang)) { List<String> euroLangs = Arrays.asList("en", "fr", "de", "es", "it", "pl", "uk"); List<String> sssrLangs = Arrays.asList("hy", "az", "ka", "lv", "lt", "md", "tk"); if (euroLangs.contains(targetLang)) targetLang = "values"; else if (sssrLangs.contains(targetLang)) targetLang = "ru"; else targetLang = "uz"; } File file = "values".equals(targetLang) ? new File("src/main/res_joke/values/strings_joke.xml") : new File("src/main/res_joke/values-" + targetLang + "/strings_joke.xml"); if (!file.exists()) file = new File("src/main/res_joke/values/strings_joke.xml"); if (file.exists()) { FileInputStream fis = new FileInputStream(file); XmlPullParser parser = Xml.newPullParser(); parser.setInput(fis, "UTF-8"); int eventType = parser.getEventType(); while (eventType != XmlPullParser.END_DOCUMENT) { if (eventType == XmlPullParser.START_TAG && "string".equals(parser.getName())) { String nameAttr = parser.getAttributeValue(null, "name"); if (nameAttr != null && nameAttr.startsWith("joke_c") && nameAttr.endsWith("_desc")) jokesList.add(parser.nextText()); } eventType = parser.next(); } fis.close(); } } catch (Exception e) {} if (!jokesList.isEmpty()) { Random random = new Random(); return jokesList.get(random.nextInt(jokesList.size())); } return "Normal"; }
    public static void generateAppStringOnline(final Context context, final String stringKey, final String userLanguage, final boolean isCheckboxChecked, final JokeCallback callback) { if (!isCheckboxChecked || getDatabase() == null) { callback.onResult(null); return; } String targetLang = userLanguage != null ? userLanguage.toLowerCase() : "values"; List<String> supportedLangs = Arrays.asList("ar", "be", "fa", "kk", "ky", "ru", "tg", "uz"); if (!supportedLangs.contains(targetLang)) { if (Arrays.asList("en", "fr", "de", "es", "it", "pl", "uk").contains(targetLang)) targetLang = "values"; else if (Arrays.asList("hy", "az", "ka", "lv", "lt", "md", "tk").contains(targetLang)) targetLang = "ru"; else targetLang = "uz"; } getDatabase().child(targetLang).child(stringKey).addListenerForSingleValueEvent(new ValueEventListener() { @Override public void onDataChange(DataSnapshot snapshot) { String bestText = null; long maxTimestamp = 0; for (DataSnapshot child : snapshot.getChildren()) { String text = child.child("text").getValue(String.class); Long ts = child.child("timestamp").getValue(Long.class); if (text != null && ts != null && ts > maxTimestamp) { maxTimestamp = ts; bestText = text; } } callback.onResult(bestText); } @Override public void onCancelled(DatabaseError error) { callback.onResult(null); } }); }
    public static boolean saveUserSubstitution(Context context, final String stringKey, final String userText, final String userLanguage, boolean isPremiumUser) { if (isLocked24h(context) || userText == null) return false; String cleanText = userText.trim(); int currentCount = getChangedCount(context); if (!isPremiumUser) { if (currentCount == 70) { Toast.makeText(context, "🎁 Лимити шумо тамом шуд! Вале барои хушҳолии ... 30 сатри дигар ТӮҲФА! Шумо метавонед Premium пайваст карда то 500 сатр иваз кунед бо табъи дилатон!", Toast.LENGTH_LONG).show(); } if (currentCount >= 100) { Toast.makeText(context, "👑 Сатри 101! Лимити ройгон тамом шуд! Барои ивази 500 сатр, Премиумро фаол кунед!", Toast.LENGTH_LONG).show(); return false; } } else { if (currentCount >= 500) { Toast.makeText(context, "🛑 Лимити максималии Премиум (500 сатр) ба охир расид!", Toast.LENGTH_LONG).show(); return false; } } context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE).edit().putInt("changed_strings_count", currentCount + 1).apply(); if (getDatabase() != null) { String targetLang = userLanguage != null ? userLanguage.toLowerCase() : "values"; List<String> supportedLangs = Arrays.asList("ar", "be", "fa", "kk", "ky", "ru", "tg", "uz"); if (!supportedLangs.contains(targetLang)) { if (Arrays.asList("en", "fr", "de", "es", "it", "pl", "uk").contains(targetLang)) targetLang = "values"; else if (Arrays.asList("hy", "az", "ka", "lv", "lt", "md", "tk").contains(targetLang)) targetLang = "ru"; else targetLang = "uz"; } HashMap<String, Object> stringData = new HashMap<>(); stringData.put("text", cleanText); stringData.put("timestamp", System.currentTimeMillis()); getDatabase().child(targetLang).child(stringKey).setValue(stringData); } return true; }
    public interface JokeCallback { void onResult(String resultText); }
}
