name: Auto Encode Keystore

on:
  workflow_dispatch: # Ин тугмача барои дастӣ пахш кардан аст

jobs:
  encode_job:
    runs-on: ubuntu-latest
    steps:
      # 1. Робот бо токени сайт (MY_TOKEN) лоиҳаро мекушояд
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}

      # 2. Робот бо ҳамин токени сайт SIGNING_KEY-ро автоматӣ месозад
      - name: Run Base64 and Push to Secrets
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }} # Робот токени сайтро худаш ба терминал месупорад!
        run: |
          base64 -w 0 TMessagesProj/config/release.keystore | gh secret set SIGNING_KEY -R ${{ github.repository }}
